### ISSUE TITLE
Constructing CascadingRDD

### ISSUE THREAD

**Issue by debasish83** [tresata/spark-scalding#5]
Hi,
On spark-shell I am trying to construct a CascadingRDD as follows:

val fields = new Fields(schema.split(",").toSeq :_*)
val source =SequenceFile("hdfs://nameservice1:8020/sandbox/20150526/part-01291", fields)
val rdd = CascadingRDD(sc, source)

I don't want to use --class com.twitter.Scalding.Tool for example

I am getting errors as follows:

Caused by: cascading.CascadingException: unable to load deserializer for: scala.collection.immutable.$colon$colon from: org.apache.hadoop.io.serializer.SerializationFactory
    at cascading.tuple.hadoop.TupleSerialization.getNewDeserializer(TupleSerialization.java:464)

In the demo sequence file jobs, SparkJob has been used and if I use SparkJob I have to use Tool to run it as it derives on top of scalding.Job but all my compute is spark now..why still dependency on map-reduce..

Thanks.
Deb

**Comment by debasish83** [comment]
It might be due to dependency but I recompiled with scalding 0.11.1 which was used to write the files...also we are using cdh but I don't think I compiled spark-scalding with cdh cascading yet..so those can be a issue but other than I am allowed to construct CascadingRDD without running scalding Job ?

**Comment by koertkuipers** [comment]
yes this should work.

looks like your sequence files have scala classes in them, probably
serialized using kryo.

CascadingRDD relies on cascading's serialization, not sparks. kryo is not
enabled (registered) by default.

i think you need to register kryo as a serializer by modifying the hadoop
Configuration passed into CascadingRDD. i can get you details later when i
am back at a computer. SparkJob (well really scalding's Job) does this by
default.

SparkJob does not depend on/use mapred, but i agree its not necessary to
use it. its mostly there to make the transition easier for people who are
used to Job.

Maybe we should register kryo by default for CascadingRDD to make
out-of-box experience better.

**Comment by debasish83** [comment]
Got it...Let me send the SparkJob's configuration while constructing CascadingRDD(sc, source, conf)...Althought I thought default new Configuration registers kryo by default in scalding but may be not...

**Comment by koertkuipers** [comment]
i believe this should mimic scalding's defaults for serialization:

val conf = new Configuration
conf.set("io.serializations", "org.apache.hadoop.io.serializer.WritableSerialization,cascading.tuple.hadoop.TupleSerialization,com.twitter.chill.hadoop.KryoSerialization")
conf.set("com.twitter.chill.config.configuredinstantiator", "com.twitter.scalding.serialization.KryoHadoop")
new CascadingRDD(sc, source, conf)

let me know if this works for you

**Comment by debasish83** [comment]
I don't have to set key for conf.set("com.twitter.chill.config.configuredinstantiator", "com.twitter.scalding.serialization.KryoHadoop") ?
With this setting I am getting the following error:

Caused by: com.twitter.chill.config.ConfigurationException: Could not find class for: com.twitter.scalding.serialization.KryoHadoop
    at com.twitter.chill.config.ConfiguredInstantiator.<init>(ConfiguredInstantiator.java:62)
    at com.twitter.chill.hadoop.KryoSerialization.setConf(KryoSerialization.java:69)

I can import the class com.twitter.scalding.serialization.KryoHadoop on spark-shell so it is part of --jars I provide:

scala> import com.twitter.scalding.serialization.KryoHadoop
import com.twitter.scalding.serialization.KryoHadoop

May be it is not being copied to Spark workers but I did give all the scalding dependences in spark-shell --jars option..

**Comment by debasish83** [comment]
Yup I can see the scalding files loaded as CTuple if I run local mode...in yarn mode I am getting that failure...weird..I am at Spark 1.2

**Comment by koertkuipers** [comment]
ah yes sorry we ran into this before. i forgot about this. chill uses some reflection that breaks in spark, probably a classloader issue.

instead try:
val conf = new Configuration
conf.set("io.serializations", "org.apache.hadoop.io.serializer.WritableSerialization,cascading.tuple.hadoop.TupleSerialization,com.tresata.spark.scalding.serialization.KryoSerialization")
new CascadingRDD(sc, source, conf)

**Comment by debasish83** [comment]
It worked. I made a gist for future references. Thanks a lot for the pointers.
https://gist.github.com/debasish83/0112dcea08a5ef749276
As I use it more to load scalding sequence files on Spark, I will understand more..partitions for example should be pulled from spark context right ? 
new CascadingRDD(sc, tap, conf, minPartitions)

**Comment by koertkuipers** [comment]
thats right

**Comment by debasish83** [comment]
Should I change the default CascadingRDD constructor to build Configuration with the serialization options in a PR ? That way users can build CascadingRDD out-of-box for scalding sources...The second change I would like to add is to pick minPartitions from spark context in CascadingRDD constructor...

**Comment by koertkuipers** [comment]
what do you think?
​i originally left that out since CascadingRDD can also be used by people
that come from a pure cascading background, in which the scalding defaults
are not necessary the right ones. but it does seem to make it harder to use
(you are not the first to run into this issue).

the second one makes sense to me, just as it makes sense to me that the
default configuration should be sc.hadoopConfiguration, instead of new
Configuration. my frustration is that you cannot say:
class CascadingRDD(@transient sc: SparkContext, tap: HadoopTap, @transient
conf: Configuration = sc.hadoopConfiguration, minPartitions: Int =
sc.defaultMinPartitions)

**Comment by debasish83** [comment]
I have to look into SequenceFile RDD in spark core and understand how does it pick up Hadoop configuration and numPartitions...we should use similar idea right ?

**Comment by debasish83** [comment]
Did you pass a object / class to CascadingRDD.map{ x => MyObj.func1(x) } in tests ? I am getting serialization error with "java.io.NotSerializableException: org.apache.hadoop.conf.Configuration"

**Comment by debasish83** [comment]
Will the private variables from CascadingRDD get serialized if I broadcast an object ? This is the only code from CascadingRDD that uses org.apache.hadoop.conf.Configuration:
   private val serializedJob = new SerializableWritable(new JobConf(conf))

**Comment by debasish83** [comment]
There might be issues in HadoopConf broadcast...why are u not broadcasting Configuration like HadoopRDD.scala ?

**Comment by koertkuipers** [comment]
can you provide some more detail about when you get "java.io.NotSerializableException: org.apache.hadoop.conf.Configuration"?

serializedJob should not cause any issues with serialization.

**Comment by debasish83** [comment]
I am doing something like this:
object Utils{
def f1(x:String) : String {}
}
val rdd = cascadingrdd(sc, source, conf)
rdd.map{case(x)=> Utils.f1(x)}
This fails on hadoop conf serialization

Now if I use mapPartitions and define f1(x) inside closure job runs fine...

**Comment by koertkuipers** [comment]
we do lots of map operations on CascadingRDD without these issues. what is
the full stacktrace? is this on the REPL?

**Comment by debasish83** [comment]
Yes its on repl...let me try it in code...the exact pattern I showed works for you ?

**Comment by koertkuipers** [comment]
yes the pattern works for me in a unit test.

the repl can be tricky, since it has a tendency to suck everything into
serialization. is the hadoop Configuration defined on the repl?

**Comment by debasish83** [comment]
Yup

**Comment by debasish83** [comment]
Repl might be the issue then.. I will try in code and update

**Comment by debasish83** [comment]
Yup issues got fixed when I added the changes in the code...sometime I do see that breaking the lineage helps but I have not yet been able to consistently reproduce the issue. I will open up the issue when I find it.
